drivers: staging: prima: Fix a qcacld-3.0 commit port derp
Changes done by the following commit:
  https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/wlan/prima/commit/?h=LA.UM.7.6.r1-06700-89xx.0&id=626f8655c62c0b61d0bcba19b6230046da76e891

Causes a compilation error, which is later traced from (probably) a
mismerge from CAF side. This commit does the following changes:
 * Correct the mismerge by placing the redundant break at its proper place.
 * Guard eLIM_AUTH_SAE_TIMER under WLAN_FEATURE_LFR_MBB.

Error log:
  /mnt/ssd/kernels/mido/drivers/staging/prima/CORE/MAC/src/pe/lim/limTimerUtils.c:1956:10: error: use of undeclared identifier 'eLIM_AUTH_SAE_TIMER'
      case eLIM_AUTH_SAE_TIMER:
           ^
  1 error generated.

Signed-off-by: Albert I <kras@raphielgang.org>